# Taken from Alembic repo on Github:
# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation


# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- vendor

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
markdown: kramdown
paginate: 5
paginate_path: /blog/page:num
sass:
  style: compressed
  sass_dir: _sass

# 4. Jekyll settings
permalink: /feed/:year/:month/:day/:title
excerpt_separator: <!--more-->

# 5. Collections
collections:
  coffee_shops:
    title: "Coffee Shops"
    output: true
    description: "The coffee shops of Cincinnati"
  courses:
    title: "Training Courses"
    output: true
    description: "Courses I teach"
  books:
    title: "Books"
    output: false
    description: "Books I've read"


# 7. Site settings
#theme: alembic-jekyll-theme
encoding: utf-8 # Make sure the encoding is right
title: "ethanswan.com"
baseurl: ""
name: Ethan Swan
repo: "https://github.com/eswan18/eswan18.github.io"
repository: "eswan18/eswan18.github.io"
email: "ethanpswan@gmail.com"

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo_dark@16px.jpeg'
  32: '/assets/logos/logo_dark@32px.jpeg'
  96: '/assets/logos/logo_dark@96px.jpeg'
  120: '/assets/logos/logo_dark@120px.jpeg'
  144: '/assets/logos/logo_dark@144px.jpeg'
  180: '/assets/logos/logo_dark@180px.jpeg'
logo: '/assets/logos/logo_light@96px.jpeg'

# 9. Site navigation
navigation_header:
  Blog: /
  Courses: /courses/
  Recommended Content: /recommended_content/
  Coffee Shop Ratings: /coffee_shop_ratings/
  About Me: /about_me/
social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/eswan18
  LinkedIn: https://www.linkedin.com/in/ethanpswan
  GitHub: https://github.com/eswan18
RSS: /feed.xml

# 10. Default Frontmatter
defaults:
  -
    scope:
      path: ""
    values:
      aside: True
  -
    scope:
      path: "courses"
    values:
      aside-type: courses
